controller:
  hero_chassis_controller:
    type: hero_chassis_controller/HeroChassisController
    pid1: { p: 40000.0, i: 600.0, d: 60.0 }
    pid2: { p: 40000.0, i: 600.0, d: 60.0 }
    pid3: { p: 40000.0, i: 600.0, d: 60.0 }
    pid4: { p: 40000.0, i: 600.0, d: 60.0 }
    Wheel_Track: 0.500
    Wheel_Base: 0.475
    Odom_Framecoordinate_Mode: True
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
