controller:
  hero_chassis_controller:
    type: hero_chassis_controller/HeroChassisController
    pid1: { p: 50000.0, i: 600.0, d: 20.0 }
    pid2: { p: 50000.0, i: 600.0, d: 20.0 }
    pid3: { p: 50000.0, i: 600.0, d: 20.0 }
    pid4: { p: 50000.0, i: 600.0, d: 20.0 }
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
